### ISSUE TITLE
Allow cfn-sphere to add validation schema

### ISSUE THREAD

**Issue by eduaquiles** [cfn-sphere/cfn-sphere#166]
We want to enforce that all CloudWatch alarms that we define have an alarm description field, even though it is not required for AWS. It would be nice if one could supply a file to cfn-sphere so that it performs this validations on the stack. (maybe extra python scripts that we can hook to cfn?).

Currently we are planning to go over our yaml files and fail the build pipeline as a quick solution.

**Comment by marco-hoyer** [comment]
Hi, this sounds interesting. I would like to know more about you use case. How would you like to enforce usage of this validation? Would it maybe be appropriate to place a config file in the executing users home dir or set an environment variable pointing to something like a script hook? Or shall it be in the stack config file?

I think about this as a generic thing where cfn-sphere could pass the template to to an external program for validation on every create/update of a stack.

**Comment by marco-hoyer** [comment]
I tested an approach with a python based validation engine in the past which allows you to define rules in a specific format but this turned out to be rather complex for users. Having a script to be executed prior to updates might be a better solution but I have some security concerns about this. At least if it happens automatically. It might be ok if it is configured in stack config but might not be what you want.
