### ISSUE TITLE
Prefix stack items with stack name

### ISSUE THREAD

**Issue by cwr10010** [cfn-sphere/cfn-sphere#24]
As the list of items from different stacks getting more and more it might be useful to differentiate these by their stack name. In order to prevent typos CFN-Sphere should be able to do this prefixing automatically based on the name of the stack in the parameters file. This would have another benefit: we are able to roll out multiple stacks with the same templates (eg. dev, testing, live)

**Comment by marco-hoyer** [comment]
The stack-configuration yml already contains the defined stack-names. Adding automagic to prefix the stacks would break consistency in the stack-configuration file without any advantage I could see. You can define multiple stacks using the same template and thus create stacks for different environments based on the same infrastructure definition by design. Let's discuss some detailed use cases to check if we need something like prefixing.

**Comment by cwr10010** [comment]
Yes wen can talk about it. I am also not sure if we need it. It is just to give some more convenience within the AWS functionality to see automatically which stack one is assigned to

**Comment by marco-hoyer** [comment]
I don't see any reason for another abstraction layer here which would make it much harder to understand stack references f.e. since one would always need to add the prefix to stackname in mind to match references. Furthermore users are simply able to prefix stack names in their stack configuration by hand.
