### ISSUE TITLE
CLI Stack parameter syntax

### ISSUE THREAD

**Issue by marco-hoyer** [cfn-sphere/cfn-sphere#52]
The implementation of the cli parameter "--parameters" done in https://github.com/cfn-sphere/cfn-sphere/pull/50 uses the following syntax: `my-stack:my-parameter=foo` but the syntax for stack referencing in stack-configuration is `my-stack.my-output`. I think that both should use equal syntax.

**Comment by marco-hoyer** [comment]
@cfn-sphere/contributors, what's your opinion?

**Comment by esc** [comment]
I'd prefer a ``.`` too. I think this would make it consistent with other uses.

**Comment by konz** [comment]
+1

**Comment by marco-hoyer** [comment]
done :-)

**Comment by esc** [comment]
The following came up during review:

The values may contain a comma `,` and thus the mini-dsl ``<stack>.<parameter>=<value>,<stack>.<parameter>=<value>`` may not be a good idea because the `,` is used to separate parameters.

One possible solution is: to use multiple ``--parameter`` arguments, one for each parameter to update.

**Comment by esc** [comment]
Also, we should probably test the command-line interface for all possible parameter and value types to ensure full compatibility with cloudformation.

**Comment by marco-hoyer** [comment]
One is now able to provide multiple parameters with `--parameter stack.parameter=value` used multiple times in a command call. This is also covered by the integration test.
