### ISSUE TITLE
allow |Ref| to output of all active stacks (not just in same file)

### ISSUE THREAD

**Issue by matey-jack** [cfn-sphere/cfn-sphere#76]
If a write in a template |Ref|someStack.someOutput, I would expect cfn-sphere to resolve this by querying the stack using AWS API.

http://boto3.readthedocs.org/en/latest/reference/services/cloudformation.html?highlight=cloudformation#CloudFormation.Client.describe_stacks
- query for name of stack
- filter for active stacks
- (there should be exactly one)
- take the output from the response-json of the above call.

As there is only one boto call to add, this shouldn't be too hard, but save us a lot of work.

**Comment by schlomo** [comment]
I don't entirely understand your problem. It is already possible to refer to output values of other stacks, regardless if they are part of the stacks.yaml or not. The reason for that is the current implementation which simply loads all output values of all stacks running in the same region.

**Comment by marco-hoyer** [comment]
Hi @matey-jack, do you want this to work inside a template? You're already able to reference other stacks outputs in the stack configuration and pass them as parameters to your stack in the way you want. This is something I would not want to do inside a template since wireing stack parameters with other stacks outputs gives a clean interface for dependency management between the stacks. See her e for details: https://github.com/cfn-sphere/cfn-sphere/wiki/Stack-Dependency-Management and https://github.com/cfn-sphere/cfn-sphere/wiki/StackConfig-Reference#cross-stack-referencing for details.

**Comment by marco-hoyer** [comment]
A, reading the headline clarifies your intention. As schlomo said, this is already possible but keep in mind that there is per design no dependency management done by cfn-sphere per design. If you update stack A which leads to a change in it's output which is also used in stack B which is not defined in the same stack configuration file, you will have to keep track of the changes yourself and manually update stack B.

**Comment by matey-jack** [comment]
Ooops, I tried it out the wrong way. Now I fixed it and all of a sudden everything works! ;-)
